language: python

python:
  - 2.7

install:
   # This is a dependency of our Django quicktest script
 - pip install argparse --use-mirrors

 - pip install -r requirements.txt

 - pip install coverage

 - pip install flake8 --use-mirrors

 - python setup.py develop

before_script:
 - flake8 --ignore=E501 mapentity

script:
 - python quicktest.py mapentity
 - coverage run quicktest.py mapentity

after_success:
 - pip install coveralls
 - coveralls
